version: 2

models:
  - name: test_binary_to_address
    tests:
      - assert_equal:
          actual: actual
          expected: expected

  - name: test_hex
    tests:
      - assert_equal:
          actual: actual
          expected: expected

  - name: test_displayed_amount
    tests:
      - assert_equal:
          actual: actual
          expected: expected

  - name: test_substring
    tests:
      - assert_equal:
          actual: actual
          expected: expected